repos:
  - repo: https://github.com/ambv/black
    rev: 23.7.0
    hooks:
    - id: black
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 'v0.1.6'
    hooks:
      - id: ruff
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.7.0
    hooks:
      - id: nbqa-black
        additional_dependencies: [jupytext, black]
      - id: nbqa-isort
      - id: nbqa-ruff