name: Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Release
        uses: tttc3/action_update_python_project@main
        with:
            enabled_features: "tag, deploy"
            python-version: "3.12"
            test-script: |
                cp -r ${{ github.workspace }}/tests ./tests
                cp ${{ github.workspace }}/pyproject.toml ./pyproject.toml
                python -m pip install -r ./tests/requirements-test.txt
                pytest
            pypi-token: ${{ secrets.pypi_token }}
            github-user: tttc3
            github-token: ${{ github.token }}
