name: Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Release
        uses: tttc3/action_update_python_project
        with:
            python-version: "3.12"
            test-script: |
                cp -r ${{ github.workspace }}/tests ./tests
                cp ${{ github.workspace }}/pyproject.toml ./pyproject.toml
                python -m pip install ".[test]"
                pytest
            pypi-token: ${{ secrets.pypi_token }}
            github-user: tttc3
            github-token: ${{ github.token }}
            email-user: ${{ secrets.email_user }}
            email-token: ${{ secrets.email_token }}
            email-server: ${{ secrets.email_server }}
            email-target: ${{ secrets.email_target }}
            email-starttls: true
