name: Run tests

on:
  pull_request:

jobs:
  run-tests:
    strategy:
      matrix:
        python-version: [ 3.9, 3.12 ]
        os: [ ubuntu-latest, windows-latest ]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r ./tests/requirements-test.txt
          
      - name: Checks with pre-commit
        uses: pre-commit/action@v3.0.0

      - name: Test with pytest
        run: |
          python -m pip install .
          pytest
